(application) Updated with customtkinter; Volume Controls and major-minor improvements
nomandhoni-cs/blink-eye pull request #34
Opened 2024-04-03 10:27 UTC by Sayad-Uddin-Tahsin

- Added Volume Mute on Session Break
- Added Fade in and out transition to sound
- Fixed `Skip this time` timer issue-
  Previously in the case of skip the remaining 20 seconds used to add with the next 20 minute on interval.
- Removed `blink-eye-reminder-btn.png` and used Button instead with 2 skip images (for `dark` and `light` mode)
- Changed fonts on Break Screen
- Changed the spacing on the links at the bottom of break screen
- Break screen now synced with System Theme (`dark` and `light`) as well as the widgets color on it
- Modified links to once clickable in one break screen
- Added `hold_the_program` instead of `time.sleep` to wait the program in order to exclude remaining time in the case of `skip`
- Removed `--icon` for Fedora, as [fluentmoheshwar](https://github.com/fluentmoheshwar) on #29 https://github.com/nomandhoni-cs/blink-eye/pull/29#pullrequestreview-1975546330

2024-04-03 11:18 UTC, fluentmoheshwar commented
Please don't merge until I review it. I have to wait until the electricity comes back to test it.

2024-04-03 11:22 UTC, fluentmoheshwar commented
Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.

2024-04-03 11:30 UTC, Sayad-Uddin-Tahsin commented
> Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.

What font you're trying to mean?

2024-04-03 11:31 UTC, Sayad-Uddin-Tahsin commented
> > Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.
> 
> What font you're trying to mean?

Do we have Helvetica on Fedora? Segoe UI seems really cool to see so added, it's changeable obviously!

2024-04-03 11:38 UTC, fluentmoheshwar commented
> > > Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.
> > 
> > What font you're trying to mean?
> 
> Do we have Helvetica on Fedora? Segoe UI seems really cool to see so added, it's changeable obviously! 

Helvatica isn't pre-installed on Fedora. The ideal solution would be

- Segoe UI on Windows
- Cantarell on Fedora/Debian/Opensuse and others
- Ubuntu on Ubuntu
- SF Pro on macOS

2024-04-03 11:38 UTC, Sayad-Uddin-Tahsin commented
> > > > Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.
> > > 
> > > 
> > > What font you're trying to mean?
> > 
> > 
> > Do we have Helvetica on Fedora? Segoe UI seems really cool to see so added, it's changeable obviously!
> 
> Helvatica isn't pre-installed on Fedora. The ideal solution would be
> 
> * Segoe UI on Windows
> * Cantarell on Fedora/Debian/Opensuse and others
> * Ubuntu on Ubuntu
> * SF Pro on macOS

In that case use of which would be ideal? Helvetica was used before!

2024-04-03 11:40 UTC, fluentmoheshwar commented
> > > > > Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.
> > > > 
> > > > 
> > > > What font you're trying to mean?
> > > 
> > > 
> > > Do we have Helvetica on Fedora? Segoe UI seems really cool to see so added, it's changeable obviously!
> > 
> > Helvatica isn't pre-installed on Fedora. The ideal solution would be
> > 
> > * Segoe UI on Windows
> > * Cantarell on Fedora/Debian/Opensuse and others
> > * Ubuntu on Ubuntu
> > * SF Pro on macOS
> 
> In that case use of which would be ideal? Helvetica was used before! 

is there any way to add fallback fonts like we do in CSS? I never really worked with tkinter.

2024-04-03 11:46 UTC, Sayad-Uddin-Tahsin commented
> > > > > > > > Anyway, I have read the code with my phone. Can we add multiple fonts? As we don't have Segoe UI in fedora.
> > > > > > > 
> > > > > > > 
> > > > > > > What font you're trying to mean?
> > > > > > 
> > > > > > 
> > > > > > Do we have Helvetica on Fedora? Segoe UI seems really cool to see so added, it's changeable obviously!
> > > > > 
> > > > > 
> > > > > Helvatica isn't pre-installed on Fedora. The ideal solution would be
> > > > > 
> > > > > * Segoe UI on Windows
> > > > > * Cantarell on Fedora/Debian/Opensuse and others
> > > > > * Ubuntu on Ubuntu
> > > > > * SF Pro on macOS
> > > > 
> > > > 
> > > > In that case use of which would be ideal? Helvetica was used before!
> > > 
> > > 
> > > is there any way to add fallback fonts like we do in CSS? I never really worked with tkinter.
> > 
> > 
> > Maybe we can import font from `.ttf` file! I'll commit the changes with the modification later. Can you just review Fedora things, especially the spec file?
> 
> Okay! I have reviewed it. But I want to run the script and test but I don't have electricity right now. I will test and review immediately after the electricity come back. Anyway if you want to use ".ttf" files don't use something like Segoe UI. It will cause licensing issues. Use a font that's open source like Noto Sans or Ubuntu.

Roger that! 🫡

2024-04-03 12:30 UTC, fluentmoheshwar commented
Build script needs to be changed and comtypes isn't available on linux

2024-04-03 14:24 UTC, Sayad-Uddin-Tahsin commented
> Build script needs to be changed and comtypes isn't available on linux

In that case, volume feature might not be available for Linux! Is there any way you know which is OS Independent? I can't find any actually...

2024-04-03 14:25 UTC, Sayad-Uddin-Tahsin commented
> Update `BlinkEye_Fedora.spec` to this:
> 
> ```python
> Name:           BlinkEye
> Version:        1.4.0
> Release:        1%{?dist}
> Summary:        Blink Eye is a minimalist eye care reminder app designed to reduce eye strain during extended screen usage.
> 
> License:        MIT
> URL:            https://github.com/nomandhoni-cs/blink-eye
> 
> %description
> Blink Eye is a minimalist eye care reminder app designed to reduce eye strain during extended screen usage. It provides customization timers, full-screen popups, audio mute functionality for a seamless user experience.
> 
> %install
> rm -rf $RPM_BUILD_ROOT
> mkdir -p $RPM_BUILD_ROOT/%{_bindir}
> cp dist/%{name} $RPM_BUILD_ROOT/%{_bindir}
> 
> %clean
> rm -rf $RPM_BUILD_ROOT
> 
> %files
> %{_bindir}/%{name}
> %license LICENSE.txt
> 
> %changelog
> * Mon Apr 01 2024 Moheshwar Amarnath Biswas
> - First Linux Version
> ```
> 
> and `build_fedora.sh` to this:
> 
> ```shell
> #!/usr/bin/env bash
> 
> ver="1.4.0"
> 
> echo Installing Dependencies...
> sudo dnf install -y rpmdevtools rpmlint python3-devel python3-pip python3-tkinter
> pip install wheel
> pip install -r REQUIREMENTS.txt
> pip install pyinstaller
> echo Building the executable...
> pyinstaller --name BlinkEye --onefile --windowed --add-data="./Assets/*:./Assets" --hidden-import plyer.platforms.linux.notification --clean blink-eye.py
> echo Building the installer...
> rpmdev-setuptree
> cp -r ./* ~/rpmbuild/BUILD
> cp ../LICENSE.txt ~/rpmbuild/BUILD/LICENSE.txt
> rpmbuild -bb ./BlinkEye_Fedora.spec
> rm -rf ~/rpmbuild/BUILD
> mkdir -p ./ExecutableFile/
> mv ~/rpmbuild/RPMS/x86_64/BlinkEye-$ver-1.fc39.x86_64.rpm ./ExecutableFile/BlinkEye-$ver-1.fc39.x86_64.rpm
> ```
> 
> and if else block to stop importing `comtypes` on macOS and Linux

The spec file won't be able to access the LINCENSE.txt as it's one step back in PATH, I think? Should I still edit it?

2024-04-03 14:28 UTC, fluentmoheshwar commented
> > Update `BlinkEye_Fedora.spec` to this:
> > 
> > ```python
> > Name:           BlinkEye
> > Version:        1.4.0
> > Release:        1%{?dist}
> > Summary:        Blink Eye is a minimalist eye care reminder app designed to reduce eye strain during extended screen usage.
> > 
> > License:        MIT
> > URL:            https://github.com/nomandhoni-cs/blink-eye
> > 
> > %description
> > Blink Eye is a minimalist eye care reminder app designed to reduce eye strain during extended screen usage. It provides customization timers, full-screen popups, audio mute functionality for a seamless user experience.
> > 
> > %install
> > rm -rf $RPM_BUILD_ROOT
> > mkdir -p $RPM_BUILD_ROOT/%{_bindir}
> > cp dist/%{name} $RPM_BUILD_ROOT/%{_bindir}
> > 
> > %clean
> > rm -rf $RPM_BUILD_ROOT
> > 
> > %files
> > %{_bindir}/%{name}
> > %license LICENSE.txt
> > 
> > %changelog
> > * Mon Apr 01 2024 Moheshwar Amarnath Biswas
> > - First Linux Version
> > ```
> > 
> > and `build_fedora.sh` to this:
> > 
> > ```shell
> > #!/usr/bin/env bash
> > 
> > ver="1.4.0"
> > 
> > echo Installing Dependencies...
> > sudo dnf install -y rpmdevtools rpmlint python3-devel python3-pip python3-tkinter
> > pip install wheel
> > pip install -r REQUIREMENTS.txt
> > pip install pyinstaller
> > echo Building the executable...
> > pyinstaller --name BlinkEye --onefile --windowed --add-data="./Assets/*:./Assets" --hidden-import plyer.platforms.linux.notification --clean blink-eye.py
> > echo Building the installer...
> > rpmdev-setuptree
> > cp -r ./* ~/rpmbuild/BUILD
> > cp ../LICENSE.txt ~/rpmbuild/BUILD/LICENSE.txt
> > rpmbuild -bb ./BlinkEye_Fedora.spec
> > rm -rf ~/rpmbuild/BUILD
> > mkdir -p ./ExecutableFile/
> > mv ~/rpmbuild/RPMS/x86_64/BlinkEye-$ver-1.fc39.x86_64.rpm ./ExecutableFile/BlinkEye-$ver-1.fc39.x86_64.rpm
> > ```
> > 
> > and if else block to stop importing `comtypes` on macOS and Linux
> 
> The spec file won't be able to access the LINCENSE.txt as it's one step back in PATH, I think? Should I still edit it? 

The spec file isn't reading from current directory it's reading from `~/rpmbuild/BUILD` don't edit it

2024-04-03 14:32 UTC, fluentmoheshwar commented
> > Build script needs to be changed and comtypes isn't available on linux
> 
> In that case, volume feature might not be available for Linux! Is there any way you know which is OS Independent? I can't find any actually... 

I can't find any either.

2024-04-03 16:18 UTC, fluentmoheshwar approved these changes
LGTM! You should add if else statement to comtype imports and merge it we can make that feature cross platform later

2024-04-03 16:19 UTC, Sayad-Uddin-Tahsin commented
> LGTM! You should add if else statement to comtype imports and merge it we can make that feature cross platform later

Yeah thinking to do so, trying to figure out the exception type!

2024-04-03 16:23 UTC, fluentmoheshwar commented
> > LGTM! You should add if else statement to comtype imports and merge it we can make that feature cross platform later
> 
> Yeah thinking to do so, trying to figure out the exception type! 

You should try something like this

```python
import platform
if platform.system == "Windows":
  # import comtypes and implement volume feature
```

2024-04-03 18:58 UTC, Sayad-Uddin-Tahsin commented
@nomandhoni-cs Please review the Website change. And allow us to view the preview web, as it helps to see the changes and debug!

2024-04-04 13:37 UTC, fluentmoheshwar commented
> @fluentmoheshwar, on the latest commit, tried to add font import mechanism but failed miserably. But added the font path everywhere the font to be used, so that it could easily be identifiable what are meant to be used. Currently it should use the default OS font.
> 
> I hope it's totally ok!

Let it use default os font

2024-04-05 13:42 UTC, Sayad-Uddin-Tahsin commented
@fluentmoheshwar Done! It will import `NotoSans-Regular` and `Consolas` font on use!

2024-04-05 14:00 UTC, fluentmoheshwar commented
> @fluentmoheshwar Done! It will import `NotoSans-Regular` and `Consolas` font on use! 

Awesome!

2024-04-05 22:56 UTC, nomandhoni-cs requested changes

2024-04-05 22:56 UTC, nomandhoni-cs commented on application/blink-eye.py
> +customtkinter.FontManager.load_font(resource_path("NotoSans-Regular.ttf"))
```suggestion
ctk.FontManager.load_font(resource_path("NotoSans-Regular.ttf"))
```

2024-04-05 22:56 UTC, nomandhoni-cs commented on application/blink-eye.py
> +customtkinter.FontManager.load_font(resource_path("Consolas.ttf"))
```suggestion
ctk.FontManager.load_font(resource_path("Consolas.ttf"))
```

2024-04-05 23:26 UTC, nomandhoni-cs commented
![Screenshot_36](https://github.com/nomandhoni-cs/blink-eye/assets/92979541/57277c0b-7dfa-4355-801a-61f4dd833014)

I have tested your changes.
This was the major problem, this wasn't creating a full screen reminder.
this was most probably because of `customtkinter`

# Issues with the new changes you made,
- Not creating a fullscreen popup
- Remove the app name and logo from the popup, our target is keep it as minimal as possible
- Change the new skip this time btn to match the previous theme

Here is our figma file, you can color code and icon and spacing from here

https://www.figma.com/file/8GenlMVGFGTpo2dLzVkyh0/Blink-Eye?type=design&node-id=21%3A7&mode=design&t=q3WCB2XnOM7sgfMC-1

2024-04-06 05:14 UTC, Sayad-Uddin-Tahsin commented
> ![Screenshot_36](https://private-user-images.githubusercontent.com/92979541/320157478-57277c0b-7dfa-4355-801a-61f4dd833014.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODA0NTgsIm5iZiI6MTcxMjM4MDE1OCwicGF0aCI6Ii85Mjk3OTU0MS8zMjAxNTc0NzgtNTcyNzdjMGItN2RmYS00MzU1LTgwMWEtNjFmNGRkODMzMDE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MTMxZGRkNDc2NjJmY2Y3NjEyOWQ5MWE0ZmIzNDVhNjAzNDEzZGQ3YmYwZGVhOGJjM2M4OTFlZTU4Mzk2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_GRxBFc8taonOJlehG_5W44T9-c-7f2CdFYu4vSqs4)
> 
> I have tested your changes. This was the major problem, this wasn't creating a full screen reminder. this was most probably because of `customtkinter`
> 
> # Issues with the new changes you made,
> * Not creating a fullscreen popup
> * Remove the app name and logo from the popup, our target is keep it as minimal as possible
> * Change the new skip this time btn to match the previous theme
> 
> Here is our figma file, you can get color code and icon and spacing from here
> 
> https://www.figma.com/file/8GenlMVGFGTpo2dLzVkyh0/Blink-Eye?type=design&node-id=21%3A7&mode=design&t=q3WCB2XnOM7sgfMC-1

• Full screen pop up will be fixed soon in new commit from my PC and it's totally not a customtkinter issue I think.
• In my opinion, on the break screen, there is no way to get which app is showing the popup. In order to aware the user of the software's existence and some sort of promote as someone sees the break screen, they might be curious and they'll get the name of the software automatically. 
• Using Image as Button, doesn't seems professional as we can create rounded buttons with hovering colors which can't be done in Image. Will it be ok, if I match the color and icon? And use a darkish color as `hover_color`?

2024-04-06 08:15 UTC, Sayad-Uddin-Tahsin commented
> ![Screenshot_36](https://private-user-images.githubusercontent.com/92979541/320157478-57277c0b-7dfa-4355-801a-61f4dd833014.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTA3NzUsIm5iZiI6MTcxMjM5MDQ3NSwicGF0aCI6Ii85Mjk3OTU0MS8zMjAxNTc0NzgtNTcyNzdjMGItN2RmYS00MzU1LTgwMWEtNjFmNGRkODMzMDE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA4MDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGVjZmQwNDcyMGFkMGIzN2U1MTgyNzM1YTAyZjNmZGI5MjlkZmQ2MDY1ZjE4ZjA4NGQ5MmM2YTcyZWE0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_vzIqffoKtAoiVa23yvvFj8L3RZmZp4ic3Gdklfroo)
> 
> I have tested your changes. This was the major problem, this wasn't creating a full screen reminder. this was most probably because of `customtkinter`
> 
> # Issues with the new changes you made,
> * Not creating a fullscreen popup
> * Remove the app name and logo from the popup, our target is keep it as minimal as possible
> * Change the new skip this time btn to match the previous theme
> 
> Here is our figma file, you can get color code and icon and spacing from here
> 
> https://www.figma.com/file/8GenlMVGFGTpo2dLzVkyh0/Blink-Eye?type=design&node-id=21%3A7&mode=design&t=q3WCB2XnOM7sgfMC-1

I really don't know how and why it's happening, seems everything is perfect here: 
![BlinkEye Screenshot](https://github.com/nomandhoni-cs/blink-eye/assets/89304780/c673f80f-cf08-42a0-b18f-a9e3269a9acb)
While running `.py` and `.exe`, both working perfectly! Can you just try running on different PC? or just try re-executing? if both fails, can you please run `.py` and see what happens?

2024-06-23 11:22 UTC, nomandhoni-cs commented
Thanks a lot for all the efforts you put together.
And Special thanks for the volume control. Probably we will try to add a unmute button beside skip reminder btn

2024-06-23 11:22 UTC, merged

2024-06-23 13:13 UTC, Sayad-Uddin-Tahsin commented
> Thanks a lot for all the efforts you put together. And Special thanks for the volume control. Probably we will try to add a unmute button beside skip reminder btn

Great Idea!